### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [viveris/uMTP-Responder#2]
Hello, I just made a logo for your project, hope you liked it.
![umtp1](https://user-images.githubusercontent.com/35619342/38850627-39103ffc-41e0-11e8-9e1f-7f91562595c8.png)
![umtp2](https://user-images.githubusercontent.com/35619342/38850630-3e9293bc-41e0-11e8-8449-f3e0677be749.png)
Let me know if you liked it and which variation and I'll upload the files on a PR. 
Please tell me if you want to modify something,

**Comment by jfdelnero** [comment]
First Thanks for these nice logos !

In fact we are a bit concerned about the USB logo. This one is trademarked and this may eventually cause some legal issues : 

http://www.usb.org/developers/logo_license/

See page 5:
http://www.usb.org/developers/logo_license/USB-IF_Logo_Usage_Guidelines_FINAL_101917.pdf

**Comment by michaelizer** [comment]
So sorry, totally forgot about that. Check these out 
![umtpr1](https://user-images.githubusercontent.com/35619342/38971188-eb132d3a-4367-11e8-8e55-57e872a07449.png)
![umtpr2](https://user-images.githubusercontent.com/35619342/38971191-f236673a-4367-11e8-9845-577df525b51b.png)

**Comment by jfdelnero** [comment]
Yes this logo look fine !
