### ISSUE TITLE
File renaming

### ISSUE THREAD

**Issue by pcercuei** [viveris/uMTP-Responder#20]
It would be nice to implement file renaming.

If I understood correctly how it works, that means adding support for the "object set/get property value" codes, and then add code handling for the "file name" property?

**Comment by jfdelnero** [comment]
yes, plus the renaming the entry on the target file system and the local/ram db.

**Comment by jfdelnero** [comment]
@pcercuei  : files/folders renaming implemented on the trunk.

**Comment by pcercuei** [comment]
Confirmed, it works fine. Thanks!

**Comment by jfdelnero** [comment]
Not under Windows 10 apparently... I need to implement some more functions on this OS.

**Comment by jfdelnero** [comment]
Rename support fully implemented and working for all OS on the trunk.
