### ISSUE TITLE
new dir error  on win7(chinese)

### ISSUE THREAD

**Issue by Music802** [viveris/uMTP-Responder#21]
Hi. New dir error on win7(chinese).  is it not support  Chinese?

**Comment by jfdelnero** [comment]
We probably need to check/fix the unicode/utf8 support. I will work on this.

**Comment by Music802** [comment]
Yes, i have try to fixed  it with iconv. 
can uMTP-Responder support Rename and other featurs like android MTP?

**Comment by jfdelnero** [comment]
The new version on the trunk now support properly the unicode files/folders names. 
Please try it and let know if all is working fine.

**Comment by Music802** [comment]
Hi，this version works  well  on  win7(chinese files/folders new/copy/delete).    
One more question, Win7 's right-click context menu have not  rename item on umtprd's MTP volume. is  it need supported by umtprd?

**Comment by jfdelnero** [comment]
@Music802 : This is now fixed. The rename function is enabled under windows now.

**Comment by Music802** [comment]
Cool!, it works well!
