### ISSUE TITLE
Copy from Nautilus' Recent files

### ISSUE THREAD

**Issue by pcercuei** [viveris/uMTP-Responder#22]
Nautilus has a "Recent files" tab on the left panel.
When copying one file from this panel directly to a MTP volume, I get ```PTP_OC_ANDROID_BeginEditObject not supported``` and the copy fails.
When copying the file from the Recent tab to another folder (e.g. /tmp) then from that folder to the MTP volume, it works.

**Comment by jfdelnero** [comment]
Android operation. I will implement this once the others current issues are fixed.

**Comment by jfdelnero** [comment]
The needed Android operations are now implemented. Tested successfully on Linux mint machine.

**Comment by pcercuei** [comment]
Awesome! Thanks!

**Comment by jfdelnero** [comment]
Closing this issue. Reopen you have any issue related to this.
