### ISSUE TITLE
Files bigger than 1,9 GB do not show up for transfer in the PC

### ISSUE THREAD

**Issue by smokeythebandit** [viveris/uMTP-Responder#26]
Files that have a size larger than 1,9 Gigabyte do not show up on the client.
We've seen this happen on machines running on Windows 10 and Debian 10.
Our host machine is a IMX6 based board. We run kernel version 5.0.5 with the realtime patch applied. The filesystem on the host where the files are stored is EXT4.

**Comment by jfdelnero** [comment]
Issue fixed. 
I close this issue.
