### ISSUE TITLE
good project

### ISSUE THREAD

**Issue by 297179121** [viveris/uMTP-Responder#4]
Hi, I am a android developer, I want to import images from my DSLR to my android device, Can I use this project on android?  thanks very much

**Comment by jfdelnero** [comment]
I may be wrong but i think that any Android client already have an build-in MTP responder. From what i have read it is directly included into the kernel. 
Anway it is maybe possible to use the uMTP-Responder with Android. You will need to disable the Android MTP responder and enable the USB gadget layer.
