### ISSUE TITLE
Is there any reason for not support dwc3?

### ISSUE THREAD

**Issue by BlackholeEscaper** [viveris/uMTP-Responder#44]
We menaged add dwc3 (superspeed) support, it seems fairly easy. (just add some extra config inside init_usb_mtp_gadget())
So, Is there some limitation behind the screen? (We encountered some stable issue during test, not sure if it is related)

**Comment by jfdelnero** [comment]
No particular reason. We just didn't have the chance yet to test it properly until now.
So we are definitively interested by a pull request.

**Comment by jfdelnero** [comment]
The dwc3 / USB 3.x SuperSpeed link is now supported. (Tested on a Ultra96-V2 Zynq UltraScale board in FunctionFS mode).
set the CONFIG_USB_SS_SUPPORT flag in buildconf.h to enable the dwc3 support.
