### ISSUE TITLE
Does `umtprd` support hot plug? 

### ISSUE THREAD

**Issue by guoweilkd** [viveris/uMTP-Responder#95]
Hi,
When I run `umtprd-ffs.sh` on the board for the first time, pc can pop up the file Manager dialog. After hot plug, I need to restart `umtprd` for pop up the file Manager dialog

What do I need to do in order to implement the hot plug?

thanks

**Comment by jfdelnero** [comment]
hotplug should work without issue, especially with FunctionFS. Have you some logs ?

**Comment by guoweilkd** [comment]
thanks， I found the reason. The partial implementation of udc is incomplete, and the plug-out implementation has not been uploaded to the gadget layer
